### ISSUE TITLE
Project setup in Eclipse

### ISSUE THREAD

**Issue by bcisneros** [DevelopersDelicias/task-timer#1]
Configure your Eclipse IDE to run the project.

Add to ```.gitignore``` all files generated by Eclipse if present.

Document your steps a new section of ```README.md```.

Make sure you can run your Unit Tests and Integration Tests from Eclipse and Maven command line.

**Comment by zocles** [comment]
This could be added to .gitignore file: please check what else is missing:
You should remove the ' character before the #

'# Directories #
/build/
/bin/
target/
 
'# OS Files #
.DS_Store
 
*.class
 
'# Package Files #
*.jar
*.war
*.ear
*.db
 
'######################
'# Windows
'######################
 
'# Windows image file caches
Thumbs.db 
 
'# Folder config file
Desktop.ini
 
'######################
'# OSX
'######################
 
.DS_Store
.svn
 
'# Thumbnails
._*
 
'# Files that might appear on external disk
.Spotlight-V100
.Trashes
 
 
'######################
'# Eclipse
'######################
 
*.pydevproject
.project
.metadata
bin/**
tmp/**
tmp/**/*
*.tmp
*.bak
*.swp
*~.nib
local.properties
.classpath
.settings/
.loadpath
/src/main/resources/rebel.xml
'# External tool builders
.externalToolBuilders/
 
'# Locally stored "Eclipse launch configurations"
*.launch
 
'# CDT-specific
.cproject
 
'# PDT-specific
.buildpath

'#######################
'# IntelliJ
'#######################
.idea/
*.iml

**Comment by LuisZatarain** [comment]
Added setup steps documentation into README.md file
