### ISSUE TITLE
Fix Checkstyles for: TaskTimerView

### ISSUE THREAD

**Issue by bcisneros** [DevelopersDelicias/task-timer#10]
1. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimerView.java:3: Missing a Javadoc comment. [JavadocType]
2. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimerView.java:5:5: Missing a Javadoc comment. [JavadocMethod]
3. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimerView.java:7:5: Missing a Javadoc comment. [JavadocMethod]
4. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimerView.java:9:5: Missing a Javadoc comment. [JavadocMethod]
5. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimerView.java:11:5: Missing a Javadoc comment. [JavadocMethod]
6. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimerView.java:13:5: Missing a Javadoc comment. [JavadocMethod]
7. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimerView.java:15:5: Missing a Javadoc comment. [JavadocMethod]

**Comment by LuisZatarain** [comment]
All check-style validations are fixed.
