### ISSUE TITLE
Fix Checkstyles for: TaskTimerApplication

### ISSUE THREAD

**Issue by bcisneros** [DevelopersDelicias/task-timer#13]
1. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/TaskTimerApplication.java:0: Missing package-info.java file. [JavadocPackage]
2. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/TaskTimerApplication.java:5: Using the '.*' form of import should be avoided - javax.swing.*. [AvoidStarImport]
3. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/TaskTimerApplication.java:7: Missing a Javadoc comment. [JavadocType]
4. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/TaskTimerApplication.java:7:1: Utility classes should not have a public or default constructor. [HideUtilityClassConstructor]
5. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/TaskTimerApplication.java:9:5: Missing a Javadoc comment. [JavadocMethod]
6. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/TaskTimerApplication.java:9:29: Parameter args should be final. [FinalParameters]

**Comment by LuisZatarain** [comment]
All check-style validations are fixed except for:
[ERROR] C:\Users\luis zatarain\projects\task-timer\src\main\java\com\developersdelicias\tasktimer\TaskTimerApplication.java:10:1: Utility classes should not have a public or default constructor. [HideUtilityClassConstructor]
