### ISSUE TITLE
Fix Checkstyles for: TaskTimerAlreadyStartedException

### ISSUE THREAD

**Issue by bcisneros** [DevelopersDelicias/task-timer#7]
1. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimerAlreadyStartedException.java:0: Missing package-info.java file. [JavadocPackage]
2. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimerAlreadyStartedException.java:4: Missing a Javadoc comment. [JavadocType]

**Comment by LuisZatarain** [comment]
All check-style validations are fixed.
