### ISSUE TITLE
Fix Checkstyles for: TaskTimer

### ISSUE THREAD

**Issue by bcisneros** [DevelopersDelicias/task-timer#8]
1. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:10: Missing a Javadoc comment. [JavadocType]
2. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:12:5: Missing a Javadoc comment. [JavadocVariable]
3. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:13:5: Missing a Javadoc comment. [JavadocVariable]
4. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:14:5: Missing a Javadoc comment. [JavadocVariable]
5. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:15:5: Missing a Javadoc comment. [JavadocVariable]
6. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:16:5: Missing a Javadoc comment. [JavadocVariable]
7. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:18:5: Missing a Javadoc comment. [JavadocMethod]
8. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:18:22: Parameter view should be final. [FinalParameters]
9. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:18:36: 'view' hides a field. [HiddenField]
10. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:23:5: Method 'start' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
11. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:23:5: Missing a Javadoc comment. [JavadocMethod]
12. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:24: 'if' construct must use '{}'s. [NeedBraces]
13. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:33:5: Missing a Javadoc comment. [JavadocMethod]
14. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:41:12: '1000' is a magic number. [MagicNumber]
15. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:41:18: '1000' is a magic number. [MagicNumber]
16. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:44:5: Method 'pause' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
17. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:44:5: Missing a Javadoc comment. [JavadocMethod]
18. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:45: 'if' construct must use '{}'s. [NeedBraces]
19. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:53:5: Method 'play' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
20. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:53:5: Missing a Javadoc comment. [JavadocMethod]
21. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:54: 'if' construct must use '{}'s. [NeedBraces]
22. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:63:5: Method 'stop' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
23. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:63:5: Missing a Javadoc comment. [JavadocMethod]
24. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:64: 'if' construct must use '{}'s. [NeedBraces]
25. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:74:5: Method 'isRunning' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
26. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:74:5: Missing a Javadoc comment. [JavadocMethod]
27. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:78:5: Method 'isPaused' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
28. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:78:5: Missing a Javadoc comment. [JavadocMethod]
29. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:82:5: Method 'togglePauseAndPlay' is not designed for extension - needs to be abstract, final or empty. [DesignForExtension]
30. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:82:5: Missing a Javadoc comment. [JavadocMethod]
31. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:90: Missing a Javadoc comment. [JavadocType]
32. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:91:9: Missing a Javadoc comment. [JavadocVariable]
33. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:91:18: Missing a Javadoc comment. [JavadocVariable]
34. [ERROR] /home/circleci/repo/src/main/java/com/developersdelicias/tasktimer/model/TaskTimer.java:91:26: Missing a Javadoc comment. [JavadocVariable]

**Comment by LuisZatarain** [comment]
All check-style validations are fixed except from:
[ERROR] C:\Users\luis zatarain\projects\task-timer\src\main\java\com\developersdelicias\tasktimer\model\TaskTimer.java:50:42: 'view' hides a field. [HiddenField]
